# NumPy 

### Numerical python

Array processing package.
support large multi-dimension arrays and matrices
NumPy is a powerful library in Python used for numerical computing. It provides support for arrays, matrices, and many mathematical functions that operate on these data structures.

Array : Data structure ,that stores same datatype values.

In [6]:
list1=[1,2,'h']


In [1]:
#installing numpy liabrary
import numpy as np

In [9]:
#converting a list in to array
list2=[1,2,3,4]
arr1=np.array(list2)

In [12]:
print(list2)
arr1

[1, 2, 3, 4]


array([1, 2, 3, 4])

# Creating Arrays

In [13]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_2d 

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

## Array Attributes

In [14]:
arr2.ndim

1

In [17]:
arr3=np.array(4)
arr3.ndim # to get dimension of array
arr3

array(4)

In [21]:
arr2.size # Total number of elements.
arr2.itemsize # size of the element of the array in bytes
arr2.dtype # Type of elements in the array.
arr2.shape # Returns a tuple of dimensions.

(5,)

In [24]:
arr4=np.array([[1,2,3],[1,2,3]])
print(arr4)
arr4.shape

[[1 2 3]
 [1 2 3]]


(2, 3)

In [25]:
arr1

array([1, 2, 3, 4])

## Slicing and Indexing

In [27]:
arr1[0:]

array([1, 2, 3, 4])

In [28]:
arr1[0]=20 #to change the value

In [4]:
arr1 =np.array([1,2,4,5])

In [10]:
arr_2d=np.array([[1, 2, 3],
       [4, 5, 6]])
print(arr_2d)
arr_2d[1,1:] 


[[1 2 3]
 [4 5 6]]


array([5, 6])

## Array Initialization

In [20]:
#Arange
#new_arr=np.arange(strt,end,step)
new_arr=np.arange(1,10)
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
#linspace
#arr2=np.linspace(start,stop,cound)
arr2=np.linspace(1,5,7)
arr2

array([1.        , 1.66666667, 2.33333333, 3.        , 3.66666667,
       4.33333333, 5.        ])

In [35]:
#random.randint
arr2=np.random.randint(1,10,6)
arr2

array([2, 9, 3, 5, 7, 7])

In [ ]:
0d=scalar ;[1]
1d=vector ;[1,2,3]
2d array =matrix ;[1,2
                    3,4]
3d=tenses=[[1,2
            3,4],
           [1,2
            3,4]]

In [11]:
np.zeros((2, 3))  # 2x3 matrix of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2, 3))  # 2x3 matrix of ones


array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(3)  # 3x3 Identity matrix 1x1,2x2


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Reshaping and Resizing

In [20]:
arr=np.array([1, 2, 3, 4, 5,6])

In [21]:
arr_reshaped = arr.reshape(2,3)  # Reshape 
arr_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
arr_flat =arr_reshaped .flatten()  # Flatten 2D array to 1D
arr_flat

array([1, 2, 3, 4, 5, 6])

## Array Operations

In [27]:
arr

array([1, 2, 3, 4, 5, 6])

In [28]:
arr+10


array([11, 12, 13, 14, 15, 16])

In [29]:
arr * 10


array([10, 20, 30, 40, 50, 60])

In [32]:
arr1=np.random.randint(1,10,(2,2))
arr2=np.random.randint(1,10,(2,2))
print(arr1)
print(arr2)
np.dot(arr1,arr2)

[[7 5]
 [3 2]]
[[1 1]
 [7 7]]


array([[42, 42],
       [17, 17]])

## vstack (Vertical Stack)

vstack is used to stack arrays vertically, row-wise.

In [34]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

result = np.vstack((arr1, arr2))
result

array([[1, 2, 3],
       [4, 5, 6]])

## Horizontal Stack

hstack (Horizontal Stack)
hstack is used to stack arrays horizontally, column-wise. 

In [33]:
result = np.hstack((arr1, arr2))
result

array([[7, 5, 1, 1],
       [3, 2, 7, 7]])

## dstack


dstack is used to stack arrays in sequence along the third axis (depth-wise). It is especially useful when you want to combine multiple 2D arrays into a 3D array by stacking them along a new third dimension.

In [35]:
result = np.dstack((arr1, arr2))
result

array([[[1, 4],
        [2, 5],
        [3, 6]]])